version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    command: sh -c "sleep 10 && python manage.py migrate && gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"


  frontend:
    build: ./frontend/
    volumes:
      - static:/app/build

  gateway:
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html
      - media:/media
    depends_on:
      - backend
      - frontend
